DIF Presentation Exchange Implementation in ACA-Py
hyperledger/aries-cloudagent-python pull request #1032
Opened 2021-03-17 17:12 UTC by shaangill025

- https://identity.foundation/presentation-exchange/
- https://w3c.github.io/vc-data-model/

2021-03-19 14:52 UTC, TimoGlastra requested changes
Thanks @shaangill025. The overall structure looks good to me, but the code lacks some comments / descriptive variable names and sometimes has some very complex code structure that make it a bit hard to follow what's happening.

So I've left some comments across the code, but didn't check the complete flow yet.

2021-03-19 14:52 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +            and constraints.subject_issuer == "required"
The `is not None` is redundant I guess?

```suggestion
            constraints.subject_issuer == "required"
```

2021-03-19 14:52 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +                    predicate = True
```suggestion
            if tmp_field.predicate == "required":
            	predicate = True
```

2021-03-19 14:52 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +        match = tmp_jsonpath.find(json.loads(credential.value))
You're parsing the stringified credential for every iteration of the loop. Also from what I can see, `filter_by_field` is called multiple times for every credential.

Preferably the already parsed credential is passed. But we can at least call `json.loads` outside of the `fields.path` loop

2021-03-19 14:52 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +
I'm sorry but I have no idea what's happening here. Could you maybe add some comments / more descriptive names or restructure a bit?

2021-03-19 14:52 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +                exclude[desc_id + (tmp_dict[k][desc_id])] = {}
Same here. It's really hard to follow

2021-03-19 16:52 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch.py
> +class CustomValueField(fields.Field):
Oh and could you change the `PresentationExchError` to a `ValidationError` and move this to a more generic place? I need the same for some of the issue cred fields so would be nice to reuse this.

2021-03-22 22:08 UTC, shaangill025 commented
@TimoGlastra I have made the requested changes and added comments [especially in the apply_requirement function] to provide some clarity.

2021-03-23 14:22 UTC, shaangill025 commented
Creating new pull request against animo's cwu-bbs-main branch.

2021-03-23 14:22 UTC, closed without merging

2021-03-23 14:35 UTC, TimoGlastra approved these changes
This is perfect! Thanks @shaangill025 

I just added a comment for the last tmp_dict

2021-03-23 14:35 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch.py
> +            del data["status_active"]
```suggestion
        if "status_active" in data:
            statuses = data.get("statuses", {})
            statuses["active"] = {
            	"directive": data.get("status_active")
            }
            data["statuses"] = statuses
            del data["status_active"]
```

2021-03-23 14:35 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +                "Error creating requirement " f"inside to_requirement function, {err}"
```suggestion
                f"Error creating requirement inside to_requirement function, {err}"
```

2021-03-23 14:35 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +    tmp_dict = {}
The last tmp_dict. Maybe something like this?
```suggestion
    given_id_descriptors = {}
```

2021-03-23 14:35 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +    for k in tmp_dict.keys():
Then here:
```suggestion
    for given_id in given_id_descriptors.keys():
```

2021-03-23 14:35 UTC, TimoGlastra commented on aries_cloudagent/protocols/present_proof/presentation_exchange/pres_exch_handler.py
> +                exclude[descriptor_id + k] = {}
And here:

```suggestion
            for descriptor_id in given_id_descriptors[given_id]:
                # Add to exclude dict
                # with descriptor_id + cred.given_id as key
                exclude[descriptor_id + given_id] = {}
```