Fix: Inbound Transport is_external attribute
hyperledger/aries-cloudagent-python pull request #1792
Opened 2022-06-01 14:12 UTC by shaangill025

Signed-off-by: shaangill025 <gill.shaanjots@gmail.com>
- resolve #1790
- resolve #1791

2022-06-09 13:48 UTC, frostyfrog requested changes
Aside from the 2 things I've noted, this change looks good to me. It moves the `is_external` property to a "private variable" and makes sure it's only written upon class initialization, where the variable is now being initialized.

2022-06-09 13:48 UTC, frostyfrog commented on aries_cloudagent/transport/inbound/http.py
>      def __init__(self, host: str, port: int, create_session, **kwargs) -> None:
Should this follow the same flow as the `WsTransport` class and include `is_external` on the constructor?

2022-06-09 13:48 UTC, frostyfrog commented on aries_cloudagent/transport/inbound/http.py
> +        super().__init__("http", create_session, is_external=False, **kwargs)
If added to the constructor, this should use that value

2022-06-09 13:48 UTC, frostyfrog commented on aries_cloudagent/transport/inbound/ws.py
> +    ) -> None:
`is_external` is being defined here, but it's never used. It's not being passed to the parent class

2022-06-10 18:07 UTC, shaangill025 commented
Closing this PR due to merge issues, PR #1802 has been created with changes made here.

2022-06-10 18:07 UTC, closed without merging