did method registry
hyperledger/aries-cloudagent-python pull request #1955
Opened 2022-09-21 20:23 UTC by burdettadam

To support different did methods in plugins we need to support did method pluggability. This PR changes the default methods to be static and registered into a registry of methods at start-up. This allows plugins to define new did methods that can be registered. The bulk of changes in this PR is updating the current code to use a did method registry.

Signed-off-by: Adam Burdett <burdettadam@gmail.com>

2022-09-22 17:50 UTC, dbluhm commented
Thought provoking question: If we load a DID from the wallet that was created with a plugged in method but the current instance of ACA-Py does not have the same plugin loaded, should we fail on loading the DID or when we attempt to use the DID?

As currently structured, the DID Method includes info about key types and support for key rotation. This would need to be stored alongside DIDs in order for us to restore a DID without knowing the Method. This doesn't seem favorable so failing to load the DID seems like the right choice.

2022-09-22 17:54 UTC, dbluhm commented
Also making note of this here: the Indy wallet does not hold a reference to an injection context. This means it is unable to load the set of supported methods from the context. Many of its operations are hard coded for did:sov and did:key. This PR leaves those operations as hard coded to support did:sov and did:key and does not introduce the injection context on the Indy wallet.

2022-10-20 22:07 UTC, ianco commented
@burdettadam can you catch this one up with the latest main branch?

2022-10-22 23:17 UTC, dbluhm requested changes

2022-10-22 23:17 UTC, dbluhm commented on aries_cloudagent/wallet/did_method.py
> +    def __init__(self, name, key_types, rotation) -> None:
These parameters should have type hints on them

2022-10-25 15:08 UTC, burdettadam commented
We have a single PR with a related key type registry now, #1986. Closing this one in favor of the new one.

2022-10-25 15:08 UTC, closed without merging