Update webhook message to terse form by default, added startup flag --debug-webhooks for full form
hyperledger/aries-cloudagent-python pull request #2145
Opened 2023-02-24 22:56 UTC by victorlee0505

Related PR #1941  
Addresses Issue #2136 

Presentation Exchange now has dedicated webhook object.

added --debug-webhooks flag to toggle full Protocol State Object for development purpose.

removed --light-weight-webhook as it is now obsolete and refactored.

Signed-off-by: Victor Lee [victorlee0505@gmail.com](mailto:victorlee0505@gmail.com)

2023-02-25 21:47 UTC, victorlee0505 commented
Terse form webhook broke integration test where agent_container.py try to get **message["by_format"]** from cred exch & pres exch webhook and it no longer exist.

we might want to add startup flag --debug-webhooks to the agent

2023-02-28 21:25 UTC, ianco commented
Some tests are failing, I suspect due to the terse webhook format:

```
      future: <Task finished coro=<AriesAgent.handle_issue_credential_v2_0() done, defined at /home/indy/demo/runners/agent_container.py:229> exception=KeyError('by_format',)>
      Traceback (most recent call last):
        File "/home/indy/demo/runners/agent_container.py", line 249, in handle_issue_credential_v2_0
          if message["by_format"]["cred_offer"].get("indy"):
      KeyError: 'by_format'
```

(Not sure if they all have the same error, I just scanned for the first one)

2023-02-28 21:26 UTC, ianco requested changes
Integration tests need to be updated to either configure the verbose format, or to not rely on detailed webhooks

2023-03-05 00:13 UTC, ianco approved these changes

2023-03-06 15:03 UTC, merged