Allow Configuration Settings on a per-tenant basis
hyperledger/aries-cloudagent-python pull request #2233
Opened 2023-05-16 14:05 UTC by shaangill025

- resolve #2209
- Some changes related to getting `BaseLedger` instance from `ledger_id` won't be used right now but will be used soon with some proposed Traction features.

2023-05-17 12:16 UTC, swcurran commented
Thanks, @shaangill025 — let us know about the test failures and we’ll look at moving this forward.

2023-06-01 17:09 UTC, shaangill025 commented
@swcurran I have added the documentation, this PR is ready for review.

2023-06-02 10:37 UTC, esune commented on aries_cloudagent/multitenant/admin/routes.py
> +ACAPY_ENDORSER_FLGAS_DEPENDENT_ON_AUTHOR_ROLE = [
Small typo: `FLGAS`->`FLAGS`

2023-06-19 16:23 UTC, swcurran commented
The goal was to get this into 0.8.2, but since the developer has not been available to work on this, it may not make it.

2023-06-20 23:19 UTC, usingtechnology requested changes
I did not test the multiledger portion of this, just the tenant extra settings.

This is probably up for discussion. Should this (tenant extra settings) be a plugin? 

In any case, what is missing is the tenant managing their settings. Currently, the base wallet/admin is the one creating the settings and updating them. A tenant/sub-wallet cannot access the `/multitenancy` APIs. I think the current changes can stay, but we should have another API `/settings` (?) that requires a tenant/sub-wallet token and they can manage those settings.

2023-06-20 23:19 UTC, usingtechnology commented on Multitenancy.md
> +| ACAPY_LOG_LEVEL  |  log.level |
I believe that changing the log level will only take affect when writing to a physical log file is configured. It's not an issue, but probably wouldn't be clear to anyone. Maybe we just need a note about that limitation?

https://github.com/hyperledger/aries-cloudagent-python/blob/421c4ed6a3f750c7f30af7b85d1481a762a5acc4/aries_cloudagent/config/logging.py#L587

2023-06-20 23:19 UTC, usingtechnology commented on Multitenancy.md
> +### Per tenant settings
Awesome documentation. 👍

2023-06-20 23:19 UTC, usingtechnology commented on aries_cloudagent/multitenant/admin/routes.py
> +ACAPY_LIFECYCLE_CONFIG_FLAG_MAP = {
I wonder if we should have another map too, one that better matches config.yml ( so`auto_accept_invites`: `debug.auto_accept_invites).  I am OK with not having it and staying with the ENV_VAR format but could see the case where they are migrating an existing config.yml file contents.

2023-06-22 00:01 UTC, shaangill025 commented
@usingtechnology The requested changes have been added.

2023-06-22 23:05 UTC, usingtechnology commented
@shaangill025 - I would expect the tenant `/settings` API to update/return the small set of values not ALL of the settings. I realize your logic will only update the given set, but the API itself should NOT return all the settings. There are definitely things in there a tenant should not know. Can we limit to the set you provided? Also, I don't think those changes are persistent over restarts of the server. It doesn't appear that we are reading or writing from the wallet record (where the extra settings are initially stored).

2023-06-27 17:48 UTC, usingtechnology requested changes
Again, I haven't tested the ledger/indy_vdr changes, but the per tenant settings is almost ready to go. One simple change for the update API response.

2023-06-27 17:48 UTC, usingtechnology commented on aries_cloudagent/settings/routes.py
> +                settings_dict = _get_filtered_settings_dict(wallet_settings)
This is great, having the changes saved with the wallet settings. Only change is that the return of the update should match the return of the get. So return all of the profile settings not just the wallet settings. It should make it easier for the caller to know what all the settings are. For instance, they may cache these settings in their frontend code and returning all of the settings saves them from doing a merge...

2023-06-27 19:10 UTC, usingtechnology submitted a review, later dismissed
great work @shaangill025

2023-06-27 19:10 UTC, usingtechnology commented on Multitenancy.md
> +| ACAPY_LOG_LEVEL  |  log-level |  log.level |
love this documentation!

2023-06-27 19:10 UTC, usingtechnology commented on aries_cloudagent/settings/routes.py
> +                settings_dict = _get_filtered_settings_dict(all_settings)
works great.

2023-06-27 19:15 UTC, andrewwhitehead commented on Multitenancy.md
> +          "public_invites": true
Might be `public-invites` according to above

2023-06-28 15:51 UTC, andrewwhitehead approved these changes

2023-06-28 17:09 UTC, merged