Document the Indy SDK to Askar Migration process
hyperledger/aries-cloudagent-python pull request #2340
Opened 2023-07-21 23:08 UTC by swcurran

Signed-off-by: Stephen Curran <swcurran@gmail.com>

2023-07-21 23:09 UTC, swcurran commented
Let me know what you think of this as a migration document.  It covers both the why and the how -- borrowing heavily from the blog post type article that Alex created, and the process that @WadeBarnes uses in migrating BC Gov instances.

Suggestions welcome!

2023-07-22 01:11 UTC, dbluhm approved these changes

2023-07-24 13:35 UTC, WadeBarnes requested changes
Looks good other than the broken links to `[aries-acapy-tools]`.

2023-07-24 13:35 UTC, WadeBarnes commented on IndySDKtoAskarMigration.md
> +Askar migration script has been published in the [aries-acapy-tools] repository.
Broken link to `[aries-acapy-tools]`

2023-07-24 14:12 UTC, swcurran commented on IndySDKtoAskarMigration.md
> +Askar migration script has been published in the [aries-acapy-tools] repository.
Thanks — fixed.

2023-07-24 14:14 UTC, WadeBarnes approved these changes

2023-07-24 14:37 UTC, merged