VC DI proof request
hyperledger/aries-cloudagent-python pull request #2960
Opened 2024-05-21 18:09 UTC by sarthakvijayvergiya

Presentation request (DIF) for VC_DI credentials

2024-06-04 17:42 UTC, ianco commented
I know this is still WIP, but we need to have a description on the PR (is necessary in case anyone needs to look back on this PR in the future, and is also used for release notes).  Also it's good - if the PR is in WIP state - to make a note of what is done and what's still outstanding ...

2024-06-06 16:22 UTC, ianco commented on aries_cloudagent/protocols/present_proof/v2_0/routes.py
> +        indy_credentials = await indy_holder.get_credentials(start, count, {})
Not sure what this extra line is for, but it's breaking the "indy" credential scenario

2024-06-16 16:45 UTC, ianco commented
Also just noticed the commit is missing the DCO signoff

2024-07-11 16:35 UTC, ianco requested changes
A couple of comments to be removed (minor issue) and unit test coverage (SonarCloud reports 27 new lines in each of `aries_cloudagent/anoncreds/holder.py` and `aries_cloudagent/vc/vc_di/prove.py` that are not covered - I think 2 simple "happy path" tests could cover most of this).

Also PR description ...  (@EmadAnwer  not sure if you mentioned you can't edit the description?)

Overall looks really good!

2024-07-11 16:35 UTC, ianco commented on demo/runners/agent_container.py
> +                # TODO for a DIF presentation need to check if it is asking for an anoncreds proof ...
This comment can be removed

2024-07-11 16:35 UTC, ianco commented on aries_cloudagent/protocols/present_proof/v2_0/formats/dif/handler.py
> +        # TODO handle vc_di format in the future
This comment can be removed

2024-07-11 22:27 UTC, ianco approved these changes

2024-07-11 23:00 UTC, jamshale commented
There is quite a few things reported in sonarcloud. I don't think everything needs to be addressed but some definitely should like the unused variable and shadow variable names.

https://sonarcloud.io/project/issues?id=hyperledger_aries-cloudagent-python&pullRequest=2960&resolved=false&sinceLeakPeriod=true

2024-07-11 23:05 UTC, ianco commented
> There is quite a few things reported in sonarcloud. I don't think everything needs to be addressed but some definitely should like the unused variable and shadow variable names.
> 
> https://sonarcloud.io/project/issues?id=hyperledger_aries-cloudagent-python&pullRequest=2960&resolved=false&sinceLeakPeriod=true
> 
> Maybe have a go over and see if we can make some improvements. I think overall the code looks good and well tested.

Good catch @jamshale 

@EmadAnwer  can you review the SonarCloud report and do a bit of cleanup?  As Jamie says we don't need to address everything but take a pass and see what you think.

2024-07-11 23:05 UTC, ianco requested changes
SonarCloud as noted by Jamie

2024-07-12 05:40 UTC, EmadAnwer commented
> > There is quite a few things reported in sonarcloud. I don't think everything needs to be addressed but some definitely should like the unused variable and shadow variable names.
> > https://sonarcloud.io/project/issues?id=hyperledger_aries-cloudagent-python&pullRequest=2960&resolved=false&sinceLeakPeriod=true
> > Maybe have a go over and see if we can make some improvements. I think overall the code looks good and well tested.
> 
> Good catch @jamshale
> 
> @EmadAnwer can you review the SonarCloud report and do a bit of cleanup? As Jamie says we don't need to address everything but take a pass and see what you think.

yes sure

2024-07-12 07:00 UTC, EmadAnwer commented
> ## [![Quality Gate Passed](https://camo.githubusercontent.com/5889b9ad78888934928f8f18bb6431c836cd7cabe6c3a6a60a1a01434d67cfdb/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d7061737365642d323070782e706e67)](https://sonarcloud.io/dashboard?id=hyperledger_aries-cloudagent-python&pullRequest=2960) **Quality Gate passed**
> Issues ![](https://camo.githubusercontent.com/da77210611fad32e47ac6a36190d5e5320fe19b1c6006fae418d539fadaadc93/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f7061737365642d313670782e706e67) [12 New issues](https://sonarcloud.io/project/issues?id=hyperledger_aries-cloudagent-python&pullRequest=2960&resolved=false&sinceLeakPeriod=true) ![](https://camo.githubusercontent.com/6e7f22e3d7f9764d9cfb28e3b8ee5ebb5f711c5bb2dcec8a6db6b0d958d63134/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f61636365707465642d313670782e706e67) [0 Accepted issues](https://sonarcloud.io/project/issues?id=hyperledger_aries-cloudagent-python&pullRequest=2960&resolutions=WONTFIX)
> 
> Measures ![](https://camo.githubusercontent.com/da77210611fad32e47ac6a36190d5e5320fe19b1c6006fae418d539fadaadc93/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f7061737365642d313670782e706e67) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=hyperledger_aries-cloudagent-python&pullRequest=2960&resolved=false&sinceLeakPeriod=true) ![](https://camo.githubusercontent.com/da77210611fad32e47ac6a36190d5e5320fe19b1c6006fae418d539fadaadc93/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f7061737365642d313670782e706e67) [86.4% Coverage on New Code](https://sonarcloud.io/component_measures?id=hyperledger_aries-cloudagent-python&pullRequest=2960&metric=new_coverage&view=list) ![](https://camo.githubusercontent.com/da77210611fad32e47ac6a36190d5e5320fe19b1c6006fae418d539fadaadc93/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f7061737365642d313670782e706e67) [0.0% Duplication on New Code](https://sonarcloud.io/component_measures?id=hyperledger_aries-cloudagent-python&pullRequest=2960&metric=new_duplicated_lines_density&view=list)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=hyperledger_aries-cloudagent-python&pullRequest=2960)



> > > There is quite a few things reported in sonarcloud. I don't think everything needs to be addressed but some definitely should like the unused variable and shadow variable names.
> > > https://sonarcloud.io/project/issues?id=hyperledger_aries-cloudagent-python&pullRequest=2960&resolved=false&sinceLeakPeriod=true
> > > Maybe have a go over and see if we can make some improvements. I think overall the code looks good and well tested.
> > 
> > 
> > Good catch @jamshale
> > @EmadAnwer can you review the SonarCloud report and do a bit of cleanup? As Jamie says we don't need to address everything but take a pass and see what you think.
> 
> yes sure

@jamshale @ianco I have fixed most of it, check it please, let me know if there are any suggestions

2024-07-12 13:39 UTC, ianco approved these changes

2024-07-12 15:04 UTC, jamshale approved these changes

2024-07-12 15:05 UTC, merged

2024-07-12 15:05 UTC, jamshale commented
I'm going to merge this. Would be nice to have in the 1.0.0 release and don't predict any regressions.

2024-07-12 15:21 UTC, swcurran commented
w00t!!!  Awesome.