Feature multikey management
hyperledger/aries-cloudagent-python pull request #3246
Opened 2024-09-20 14:31 UTC by PatStLouis

Supersedes #3168.

During the last aca-py call, it was discuss that it would be preferable to create keys instead of dids for associating a verification method.

This PR adds 3 routes to the wallet and adds an optional `kid` property to the KeyInfo class.

Deleting a key should be looked at in a separate PR as this feature isn't currently supported by aca-py and could have other ramifications to be taken into account.

2024-09-20 16:09 UTC, PatStLouis commented
@jamshale I'm having issues with the linting tests. I have ruff version 0.6.5 and even if I apply formatting it's still causing errors without much details. Do you have a clue what I'm doing wrong here?

2024-09-20 16:22 UTC, jamshale commented
I think it's working correctly. Sometimes the formatter won't be able to automatically fix things.

![image](https://github.com/user-attachments/assets/70075e21-bc6a-46fd-9e19-6aafc764fd94)

The line too long is annoying sometimes. I'm fine with just adding `# noqa: E501` to these lines. The others just need doc string and we have a preference to have `is None` instead of `== None`.

Usually I just run `poetry run ruff check .` when I get a fail. There should be a vscode run option for the devcontianer as well.

2024-09-20 17:12 UTC, PatStLouis commented
now it's asking me to use version ruff==`0.5.7` but the `pyproject.toml` lists `0.6.5`

> creating virtual environment...
> installing ruff from spec 'ruff==0.5.7'...
> Would reformat: aries_cloudagent/wallet/did_info.py
> 1 file would be reformatted, 1360 files already formatted

2024-09-20 17:14 UTC, PatStLouis commented
ok I think I sorted it out this time!

2024-09-20 19:57 UTC, PatStLouis commented
@jamshale @dbluhm I'm happy with the state of this PR, every new function has a test

2024-09-22 16:33 UTC, jamshale reviewed
LGTM. I'm going to let Daniel have a look before approving.

2024-09-22 16:33 UTC, jamshale commented on aries_cloudagent/wallet/keys/manager.py
> +        prefix_lenght = ALG_MAPPINGS[alg]["prefix_lenght"]
spelling mistake

2024-09-22 16:33 UTC, jamshale commented on aries_cloudagent/wallet/keys/manager.py
> +    def _multikey_to_verkey(self, multikey, alg="ed25519"):
Could use a constant for the the default alg variable.

2024-09-22 16:33 UTC, jamshale commented on aries_cloudagent/wallet/keys/routes.py
> +        return web.json_response(key_info, status=200)
The status codes are done like this in many places, but you can also do `HTTPStatus.OK`. I think it's a bit better than just straight integers. You don't have to change it in this PR though.

2024-09-22 23:25 UTC, PatStLouis commented
Upon further testing I noticed that for it to be compatible with the askar wallet there was some slight changes required. I've implemented those.

One issue is Askar is unable for find the key given a `kid`. Has the `get_key_by_kid` function been tested with the askar wallet? If so, could someone point me towards where it's used in the code base? The only place I can find it is in the `test_in_memory_wallet.py` file.

2024-09-23 02:02 UTC, PatStLouis commented
ok I got it to work as I intended

2024-09-24 14:46 UTC, PatStLouis commented
@jamshale can you add @dbluhm as a reviewer here?

2024-09-24 14:49 UTC, jamshale commented
Done. One thing I was wondering was if we can or should do a scenario integration test for this? They are a lot quicker and easier to write than before.

2024-09-24 14:59 UTC, dbluhm requested changes
Some recommended changes

2024-09-24 14:59 UTC, dbluhm commented on aries_cloudagent/wallet/keys/manager.py
> +    async def kid_exists(self, wallet, kid):
To this point, the convention has been to accept a session rather than a session based component

2024-09-24 14:59 UTC, dbluhm commented on aries_cloudagent/wallet/keys/manager.py
> +    def _verkey_to_multikey(self, verkey, alg=DEFAULT_ALG):
Type hints would be appreciated

2024-09-24 14:59 UTC, dbluhm commented on aries_cloudagent/wallet/keys/manager.py
> +    def __init__(self, profile=Profile):
`profile=Profile` doesn't make sense; was this intended to be a type hint?

2024-09-24 14:59 UTC, dbluhm commented on aries_cloudagent/wallet/keys/manager.py
> +    async def from_kid(self, kid: str):
We should accept a session rather than open one ourselves for this kind of method

2024-09-24 14:59 UTC, dbluhm commented on aries_cloudagent/wallet/keys/manager.py
> +    async def from_multikey(self, multikey: str):
Same

2024-09-24 14:59 UTC, dbluhm commented on aries_cloudagent/wallet/keys/manager.py
> +    async def create(self, seed=None, kid=None, alg=DEFAULT_ALG):
Type hints needed. Also accepting a session is recommended.

2024-09-24 14:59 UTC, dbluhm commented on aries_cloudagent/wallet/keys/manager.py
> +    async def update(self, multikey: str, kid: str):
Accepting a session is recommended.

2024-09-24 15:32 UTC, PatStLouis commented
@dbluhm I've implemented all your recommendations, @jamshale I will have a quick look

2024-09-24 15:47 UTC, dbluhm commented on aries_cloudagent/wallet/keys/manager.py
> +        wallet: BaseWallet | None = self.session.inject_or(BaseWallet)
`inject_or` used but then we didn't check if wallet was definitely not `None`. You probably meant to use just `session.inject`, which will make sure an instance of the requested type is returned.

A few instances of this. I won't individually comment on each.

2024-09-24 17:38 UTC, PatStLouis commented
@jamshale @dbluhm if we are happy with the state of this work I would like to have it merged sooner than later to start re basing #3181

2024-09-24 17:47 UTC, jamshale reviewed
Just one comment and I'll approve.

2024-09-24 18:08 UTC, jamshale approved these changes

2024-09-24 18:14 UTC, dbluhm approved these changes

2024-09-24 18:35 UTC, merged